### PR TITLE
fix(modal): fixed modal, more identifying css

### LINKED ISSUE #29: Are you sure modal stopped working.
areYouSure variable is set to True, probably styling issue?

### PR DESCRIPTION
**Pull request by tagptroll1**
fixes #29

### CODE REVIEW

File: app/src/routes/question/_layout.svelte [hunk 1]
```diff
@@ -75,12 +75,14 @@
     left: 0;
     right: 0;
     margin: 0 auto;
-    z-index: 5;
+    z-index: 50;
```
Comment (practicalRope) [inline app/src/routes/question/_layout.svelte]: 🤔

Comment (tagptroll1) [reply app/src/routes/question/_layout.svelte]: i was test, 🤷‍♂
